name: GitHub Actions Demo
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      #- run: curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
      - run: GO_FILES=$(find . -iname '*.go' -type f) # All the .go files, excluding .github
      - run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u golang.org/x/lint/golint
          golint -set_exit_status ./...
      #- run: go get github.com/golang/lint
      #- run: go get honnef.co/go/tools/cmd/megacheck
