name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      #- run: curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
      - run: GO_FILES=$(find . -iname '*.go' -type f) # All the .go files, excluding .github
      - run: go get https://github.com/golang/lint
      #- run: go get honnef.co/go/tools/cmd/megacheck
